// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA4UKFg0Ay0O5t-NW9TVGZ7p6lBVzKk04',
    appId: '1:397980327923:web:853947e89d65d8bbe97c86',
    messagingSenderId: '397980327923',
    projectId: 'tdah-6472b',
    authDomain: 'tdah-6472b.firebaseapp.com',
    storageBucket: 'tdah-6472b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApMm9UV6F9BQTuI9ZeVt3m6-OE5ed-nKw',
    appId: '1:397980327923:android:934be9133eb1441be97c86',
    messagingSenderId: '397980327923',
    projectId: 'tdah-6472b',
    storageBucket: 'tdah-6472b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPZheDLxTZmriokiajf9-7PqYaf__-zNs',
    appId: '1:397980327923:ios:00c7a7711bdf6c78e97c86',
    messagingSenderId: '397980327923',
    projectId: 'tdah-6472b',
    storageBucket: 'tdah-6472b.firebasestorage.app',
    iosClientId: '397980327923-bhevbpo23fhkppg2aga5ptpbhc62aqc4.apps.googleusercontent.com',
    iosBundleId: 'com.example.tdahApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPZheDLxTZmriokiajf9-7PqYaf__-zNs',
    appId: '1:397980327923:ios:00c7a7711bdf6c78e97c86',
    messagingSenderId: '397980327923',
    projectId: 'tdah-6472b',
    storageBucket: 'tdah-6472b.firebasestorage.app',
    iosClientId: '397980327923-bhevbpo23fhkppg2aga5ptpbhc62aqc4.apps.googleusercontent.com',
    iosBundleId: 'com.example.tdahApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAA4UKFg0Ay0O5t-NW9TVGZ7p6lBVzKk04',
    appId: '1:397980327923:web:9a561c6c283cc722e97c86',
    messagingSenderId: '397980327923',
    projectId: 'tdah-6472b',
    authDomain: 'tdah-6472b.firebaseapp.com',
    storageBucket: 'tdah-6472b.firebasestorage.app',
  );
}
